name: Check PR
on: pull_request

jobs:
   maven:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
           with:
              submodules: true
         - uses: actions/setup-java@v4
           with:
              distribution: temurin
              java-version: 21
         - name: Run Checks
           run: ./mvnw -T 4 --batch-mode --no-transfer-progress --update-snapshots verify
